apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-local-cert
  namespace: default
spec:
  commonName: wisecow.local
  dnsNames:
  - wisecow.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretName: wisecow-local-tls
  duration: 8760h
  renewBefore: 360h

